// IMPORTANT: This file is auto-generated by Genkit. Do not modify.
// See https://firebase.google.com/docs/genkit/nextjs-api-routes

import { genkit } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';
import { NextRequest } from 'next/server';
import { Api, GENKIT_CLIENT_HEADER } from '@genkit-ai/next';

import '@/ai/flows/review-solution';
import '@/ai/flows/private-chat-flow';

genkit({
  plugins: [googleAI()],
  model: 'googleai/gemini-2.5-flash',
});

const { POST } = Api({
  isClient: (req: NextRequest) => {
    return req.headers.get(GENKIT_CLIENT_HEADER) === 'true';
  },
});

export { POST };
