// IMPORTANT: This file is auto-generated by Genkit. Do not modify.
// See https://firebase.google.com/docs/genkit/nextjs-api-routes

import { ai } from '@/ai/genkit';
import { NextRequest } from 'next/server';
import { Api, GENKIT_CLIENT_HEADER } from '@genkit-ai/next';

import '@/ai/flows/review-solution';
import '@/ai/flows/private-chat-flow';

const { POST } = Api({
  getFlow: async (slug, body) => {
    const flow = ai.registry.getFlow(slug);
    if (!flow) {
      throw new Error(`Flow not found: ${slug}`);
    }
    return flow;
  },
  isClient: (req: NextRequest) => {
    return req.headers.get(GENKIT_CLIENT_HEADER) === 'true';
  },
});

export { POST };
